# Generated by Django 2.2 on 2020-04-18 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('national', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administration',
            name='image',
            field=models.ImageField(upload_to='static/img/national'),
        ),
        migrations.AlterField(
            model_name='crime',
            name='image',
            field=models.ImageField(upload_to='static/img/national'),
        ),
        migrations.AlterField(
            model_name='economic',
            name='image',
            field=models.ImageField(upload_to='static/img/national'),
        ),
        migrations.AlterField(
            model_name='education',
            name='image',
            field=models.ImageField(upload_to='static/img/national'),
        ),
        migrations.AlterField(
            model_name='parliament',
            name='image',
            field=models.ImageField(upload_to='static/img/national'),
        ),
        migrations.AlterField(
            model_name='politic',
            name='image',
            field=models.ImageField(upload_to='static/img/national'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='image',
            field=models.ImageField(upload_to='static/img/national'),
        ),
    ]
