# Generated by Django 2.2 on 2020-04-18 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('national', '0002_auto_20200418_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='politic',
            name='image',
            field=models.ImageField(upload_to='static'),
        ),
    ]
