# Generated by Django 2.2 on 2020-04-18 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('national', '0003_auto_20200418_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administration',
            name='image',
            field=models.ImageField(upload_to='static'),
        ),
        migrations.AlterField(
            model_name='crime',
            name='image',
            field=models.ImageField(upload_to='static'),
        ),
        migrations.AlterField(
            model_name='economic',
            name='image',
            field=models.ImageField(upload_to='static'),
        ),
        migrations.AlterField(
            model_name='education',
            name='image',
            field=models.ImageField(upload_to='static'),
        ),
        migrations.AlterField(
            model_name='parliament',
            name='image',
            field=models.ImageField(upload_to='static'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='image',
            field=models.ImageField(upload_to='static'),
        ),
    ]
